montyHall_1.png:
	convert -density 300 montyHall_1.pdf -resize 66% montyHall_1.png
	convert -density 300 montyHall_2.pdf -resize 66% montyHall_2.png
	convert -density 300 montyHall_3.pdf -resize 66% montyHall_3.png
	convert -density 300 modelo_causal_0.pdf -resize 50% modelo_causal_0.png
	convert -density 300 modelo_causal_0_caminos.pdf -resize 50% modelo_causal_0_caminos.png
	convert -density 300 modelo_causal_0_conjunta.pdf -resize 50% modelo_causal_0_conjunta.png
